"""Inventory read tools — MSISDN pool + eSIM pool (hosted on CRM).

Reservation / assignment are internal SOM operations and are NOT exposed as
LLM tools — the LLM only reads availability.
"""

from __future__ import annotations

from typing import Any

from ..clients import get_clients
from ..types import Iccid, Msisdn
from ._registry import register


@register("inventory.msisdn.list_available")
async def inventory_msisdn_list_available(
    prefix: str | None = None,
    limit: int = 20,
    status: str | None = "available",
) -> list[dict[str, Any]]:
    """List MSISDNs from the inventory pool.

    Default behaviour is the order-creation use case: status filter
    pinned to ``"available"``, no prefix, first ``limit`` rows. The
    operator cockpit also uses this tool for general pool inspection,
    so the parameters are widened:

    - ``prefix`` is OPTIONAL. Omit it to return the first ``limit``
      MSISDNs regardless of leading digits. Pass a 1-12 digit string
      to filter via SQL ``startswith`` — ``prefix="8888"`` matches
      ``88880000``..``88889999``; ``prefix="8"`` matches every number
      whose MSISDN begins with 8.
    - ``status`` accepts ``"available"`` (default), ``"reserved"``,
      ``"assigned"``, ``"ported_out"``, or ``None`` for any state.
      Use ``status=None`` when the operator says "show me all
      numbers" — they want the full pool, not just the sellable
      slice.

    Args:
        prefix: Optional digit prefix, e.g. ``"9000"`` or ``"8"``.
        limit: Maximum rows (default 20).
        status: One of ``available``, ``reserved``, ``assigned``,
            ``ported_out``, or ``None`` to disable the status filter.

    Returns:
        List of MSISDN dicts
        ``{msisdn, status, reserved_at?, assigned_to_subscription_id?}``.

    Raises:
        (none expected — read tool)
    """
    return await get_clients().inventory.list_msisdns(
        state=status, prefix=prefix, limit=limit
    )


@register("inventory.msisdn.get")
async def inventory_msisdn_get(msisdn: Msisdn) -> dict[str, Any]:
    """Get status of a specific MSISDN.

    Args:
        msisdn: 8-digit mobile number.

    Returns:
        MSISDN dict ``{msisdn, state, assignedTo?, reservedUntil?}``.

    Raises:
        NotFound: MSISDN is not in the pool.
    """
    return await get_clients().inventory.get_msisdn(msisdn)


@register("inventory.esim.list_available")
async def inventory_esim_list_available(limit: int = 20) -> list[dict[str, Any]]:
    """List available eSIM profiles. Rarely needed by the LLM — order
    workflow assigns an eSIM automatically.

    Args:
        limit: Maximum rows (default 20).

    Returns:
        List of eSIM dicts ``{iccid, state}``.

    Raises:
        (none expected — read tool)
    """
    return await get_clients().inventory.list_esims(state="available", limit=limit)


@register("inventory.msisdn.count")
async def inventory_msisdn_count(
    prefix: str | None = None,
) -> dict[str, Any]:
    """Group-by-status pool count. Source of truth for "how many
    numbers do we have?" / "is that all?" follow-ups.

    The list tool truncates at ``limit`` (default 20) and does not
    expose a total. Call this whenever the operator asks about pool
    size, depth, or whether a list result is partial — never guess
    or infer from prior list output.

    ``prefix`` narrows the count to MSISDNs whose digits start with
    the given string (same ``startswith`` semantics as
    ``inventory.msisdn.list_available``); omit it for the whole pool.

    Args:
        prefix: Optional 1-12 digit prefix.

    Returns:
        ``{available, reserved, assigned, ported_out, total, prefix}``.
        Canonical state keys are always present (0 if no rows).

    Raises:
        (none expected — read tool)
    """
    return await get_clients().inventory.count_msisdns(prefix=prefix)


@register("inventory.msisdn.add_range")
async def inventory_msisdn_add_range(
    prefix: str, count: int
) -> dict[str, Any]:
    """v0.17 — bulk-extend the MSISDN pool by ``count`` contiguous numbers.

    The tool materializes the range as ``{prefix}{i:04d}`` for
    ``i in range(count)``. ``prefix`` MUST be 4-7 digits; the suffix
    is always 4 zero-padded digits, generated by the tool.

    Translating an operator's intent — IMPORTANT:

    - "add 50 numbers from 88880000" / "starting at 88880000"
        → prefix="8888", count=50 (NOT prefix="88880000"). The result
          is 88880000..88880049. Passing the full starting MSISDN as
          prefix is rejected by the policy (8 digits > the 7-digit
          maximum) and would otherwise produce 12-digit MSISDNs.
    - "add 1000 numbers under 9100"
        → prefix="9100", count=1000 (range 91000000..91000999).
    - "add the 88889999 number"
        → reject this shape: the tool only adds *contiguous ranges*.
          A single specific MSISDN is added by adding the prefix range
          that contains it (e.g. prefix="8888", count=10000).

    Operator-only: registered in the ``operator_cockpit`` profile, NOT
    in ``customer_self_serve``. Idempotent on overlap — overlapping
    ranges re-run cleanly; existing rows (including ``ported_out``)
    are preserved.

    Args:
        prefix: 4-7 digit numeric prefix, e.g. ``"9100"`` or ``"8888"``.
        count:  Numbers to add (1..10000).

    Returns:
        ``{prefix, count, inserted, skipped, first, last}``.

    Raises:
        PolicyViolation: ``msisdn.add_range.sane_prefix`` —
            non-digit prefix, prefix length outside [4, 7], or count
            outside [1, 10000].
    """
    return await get_clients().inventory.add_msisdn_range(prefix, count)


@register("inventory.esim.get_activation")
async def inventory_esim_get_activation(iccid: Iccid) -> dict[str, Any]:
    """Return the LPA activation-code record for an eSIM. Callers typically
    want this as ``{iccid, imsi, activationCode, msisdn}`` for QR rendering.
    For a subscription, prefer ``subscription.get_esim_activation`` which
    handles ICCID lookup.

    Args:
        iccid: eSIM ICCID (19-20 digits starting with ``8910101``).

    Returns:
        Activation dict.

    Raises:
        NotFound: unknown ICCID.
    """
    return await get_clients().inventory.get_activation_code(iccid)
